### ISSUE TITLE
pod update 太慢了

### ISSUE THREAD

**Issue by zxl20zxl** [TalkingData/TalkingData-AppAnalytics-SDK-iOS#1]
Cloning into 'TalkingData-AppAnalytics-SDK-iOS'...
remote: Counting objects: 54, done.
Unpacking objects:  50% (27/54)

卡在这都不动了

**Comment by RobinChao** [comment]
@zxl20zxl  在使用 **pod update** 的时候，可以加上**--no-repo-update** 参数，加快update过程。
完整命令：
```
pod update --no-repo-update
```

希望有用！

**Comment by zxl20zxl** [comment]
get
